### ISSUE TITLE
Dataset Preprocess

### ISSUE THREAD

**Issue by lisdarr** [psunlpgroup/FaMeSumm#1]
Hello, thank you for your work.
Will you provide a data set processing file later? That is, how to convert from the original dataset to the sample_datasets format you gave us.
I looked at the UMLS website, but I didn't know which API was used to extract medical terms from text.
Looking forward to your reply!

**Comment by ZN1010** [comment]
Yes, we will provide those files later. If your major concern comes from identifying medical terms by UMLS, I suggest you to check out scispacy: [https://github.com/allenai/scispacy](https://github.com/allenai/scispacy). The `EntityLinker` part is what we used in our paper to identify medical terms.

**Comment by lisdarr** [comment]
Thank you for responding. 
Additionally, regarding the MDS dataset, are there any plans to make it publicly available in the future?

**Comment by ZN1010** [comment]
> Thank you for responding.
> Additionally, regarding the MDS dataset, are there any plans to make it publicly available in the future?

We are constantly reaching out to the platform to ask for permission, but we have not obtained one yet - the same as all the related work that tried to crawl the data there (to the best of our knowledge). As a solution to this, our paper has detailed description of how we collected the data and annotated medical terms.

**Comment by ZN1010** [comment]
Hi @lisdarr ! We have added `preprocess_QS.ipynb` and `preprocess_RRS.ipynb` to show how we preprocess the English datasets. You may check the updated README (the last paragraph of the dataset section) for more details. I will close this discussion for now. Let me know if there are additional questions.
